#!/usr/bin/env node
/**
 * Phase 3 — locale page generator for thecompdesk.com.
 *
 * Reads the English source pages listed in i18n/pages.json and emits one copy per
 * locale under /<locale>/<same path>. English stays at the ROOT, untouched except for
 * the hreflang block and the locale-runtime script tag.
 *
 * Stage 3A: no catalogs exist yet, so every locale page carries English copy. That is
 * deliberate — routing and persistence get proven before content lands. Stage 3B adds
 * i18n/<locale>.json and translation turns on with no change to this file's structure.
 *
 * Generated pages are COMMITTED, not built on Vercel. The site deploys as pure static
 * with no build command; adding one would put the existing English organic footprint
 * behind a build that can fail. Re-run this script after any English source edit.
 *
 *   node scripts/i18n/build-locales.mjs           # write
 *   node scripts/i18n/build-locales.mjs --check   # verify on-disk output is current (CI gate)
 */
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const ROOT = path.resolve(new URL('../../', import.meta.url).pathname);
const ORIGIN = 'https://thecompdesk.com';
const CHECK = process.argv.includes('--check');

const locales = JSON.parse(fs.readFileSync(path.join(ROOT, 'i18n/locales.json'), 'utf8'));
const manifest = JSON.parse(fs.readFileSync(path.join(ROOT, 'i18n/pages.json'), 'utf8'));
const SLOTS_PATH = path.join(ROOT, 'i18n/.slots.json');
const SLOTS = fs.existsSync(SLOTS_PATH) ? JSON.parse(fs.readFileSync(SLOTS_PATH, 'utf8')) : {};

const TARGETS = locales.locales.filter((l) => l.prefix);          // the 9 prefixed locales
const ALL = locales.locales;                                       // incl. en at root
const PAGES = manifest.pages;
const ROUTES = new Set(PAGES.map((p) => p.route));

/** Absolute URL for a route in a locale. */
const urlFor = (route, loc) => {
  const prefix = loc.prefix || '';
  if (route === '/') return `${ORIGIN}${prefix}/`;
  return `${ORIGIN}${prefix}${route}`;
};

/** Output file path for a source file in a locale. */
const outFor = (file, loc) => path.join(ROOT, loc.prefix.slice(1), file);

/** Load a locale catalog if it exists (Stage 3B onward). Missing = identity/English. */
function loadCatalog(code) {
  const p = path.join(ROOT, 'i18n', `${code}.json`);
  if (!fs.existsSync(p)) return null;
  return JSON.parse(fs.readFileSync(p, 'utf8'));
}

/**
 * hreflang block. Emits an alternate ONLY for locales that actually have a page at a
 * real URL — which, for every page in the manifest, is all 10. Pages absent from the
 * manifest never reach this function and therefore emit nothing: an hreflang pointing
 * at untranslated content is a duplicate-content signal, strictly worse than omission.
 */
function hreflangBlock(route) {
  const lines = ['  <!-- i18n:hreflang (generated by scripts/i18n/build-locales.mjs — do not hand-edit) -->'];
  // draft locales are generated but NOT advertised — see "_draft" in i18n/locales.json.
  // Their pages exist and can be previewed; telling Google they are Arabic when they still
  // carry English copy is the duplicate-content case this function's own doc warns about.
  for (const l of ALL.filter((x) => !x.draft)) {
    lines.push(`  <link rel="alternate" hreflang="${l.code}" href="${urlFor(route, l)}">`);
  }
  lines.push(`  <link rel="alternate" hreflang="x-default" href="${urlFor(route, ALL[0])}">`);
  lines.push('  <!-- /i18n:hreflang -->');
  return lines.join('\n');
}

const HREFLANG_RE = /[ \t]*<!-- i18n:hreflang[\s\S]*?<!-- \/i18n:hreflang -->\n?/g;
const RUNTIME_RE = /[ \t]*<script src="\/js\/i18n-locale\.js" defer><\/script>\n?/g;
const RUNTIME_TAG = '  <script src="/js/i18n-locale.js" defer></script>';

/** Strip any previously-generated i18n block so the script is idempotent. */
const stripGenerated = (html) => html.replace(HREFLANG_RE, '').replace(FONTS_RE, '').replace(RUNTIME_RE, '');

/**
 * Google Fonts families a locale needs on top of DM Sans (Latin + Latin-ext only).
 *
 * DERIVED from i18n/locales.json, not authored here. This used to be a local
 * FONT_FAMILIES map — a second list that had to agree with the registry, with nothing
 * enforcing it. The app shipped that exact defect twice in Phase 4B (build-fonts.py FACES
 * vs verify-fonts.py SCRIPT_FACE), where the symptom was a no-tofu gate blaming the fonts
 * for what was really a missing map entry. A locale whose registry entry has no `fonts`
 * is a FAIL, not a silent fallback to Noto Sans: a fallback is how ar would have rendered
 * from whatever the visitor's OS happened to supply, on a page we told Google was Arabic.
 *
 * `Noto Sans` is on EVERY locale including English — it carries the arrow glyphs
 * (U+2192, and U+2190 for the RTL locales) that DM Sans lacks.
 */
function fontBlock(code) {
  const meta = ALL.find((l) => l.code === code);
  if (!meta || !Array.isArray(meta.fonts) || meta.fonts.length === 0) {
    throw new Error(
      `locale '${code}' has no "fonts" in i18n/locales.json — refusing to guess. ` +
      `A wrong or missing font stack renders the page from an OS fallback, or as tofu.`);
  }
  const q = meta.fonts.map((f) => `family=${f}:wght@400;500;600;700`).join('&');
  return [
    '  <!-- i18n:fonts (generated — do not hand-edit) -->',
    '  <link rel="stylesheet" href="/css/i18n-fonts.css">',
    '  <link rel="stylesheet" href="/css/i18n-picker.css">',
    // rtl.css LAST so its [dir="rtl"] overrides win on specificity ties. Loaded in every
    // locale, not just ar/ur: the rules are all scoped under [dir="rtl"], so it is inert
    // in LTR, and a conditional link is one more thing that can be conditionally wrong.
    '  <link rel="stylesheet" href="/css/rtl.css">',
    `  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?${q}&display=swap">`,
    '  <!-- /i18n:fonts -->',
  ].join('\n');
}

const FONTS_RE = /[ \t]*<!-- i18n:fonts[\s\S]*?<!-- \/i18n:fonts -->\n?/g;

/** Insert the hreflang block, font block, and runtime tag immediately before </head>. */
function injectHead(html, route, code) {
  const block = `${hreflangBlock(route)}\n${fontBlock(code)}\n${RUNTIME_TAG}\n`;
  const i = html.search(/<\/head>/i);
  if (i === -1) throw new Error('no </head>');
  return html.slice(0, i) + block + html.slice(i);
}

/**
 * Rewrite document-relative asset refs to absolute so they still resolve one directory
 * deeper under a locale prefix. `../css/app.css` from /calculators/aww would otherwise
 * resolve to /es/css/app.css under /es/calculators/aww and 404.
 * Deliberately skips template-literal interpolations (`${...}`) and every URL scheme.
 */
function absolutizeRefs(html, srcFile) {
  const dir = path.posix.dirname('/' + srcFile.split(path.sep).join('/'));
  return html.replace(
    /(\b(?:src|href)=")((?!https?:|\/\/|\/|#|mailto:|tel:|sms:|data:|javascript:|\$\{)[^"]+)"/g,
    (m, lead, ref) => {
      if (ref.includes('${')) return m;
      const abs = path.posix.normalize(path.posix.join(dir, ref));
      return `${lead}${abs}"`;
    },
  );
}

/**
 * 301 sources in vercel.json whose destination IS in the manifest. Following the alias
 * here keeps a locale visitor in their locale — a link to /privacy would otherwise 301
 * to the ENGLISH /legal/privacy and silently drop them out of Spanish — and saves a hop.
 * Aliases whose destination is not in the manifest (/for-attorneys, /calculators/pro,
 * /home-legacy) are absent on purpose: those pages are English-only.
 */
const ALIASES = {
  '/privacy': '/legal/privacy',
  '/terms': '/legal/terms',
  '/hire-attorney': '/connect-with-attorney',
  '/find-attorney': '/connect-with-attorney',
  '/find-attorney-how-it-works': '/connect-with-attorney',
};

/** Map any written form of a link to its canonical manifest route, or null. */
function resolveRoute(p) {
  let r = p.replace(/\.html$/, '');
  if (ALIASES[r]) r = ALIASES[r];
  if (ROUTES.has(r)) return r;
  // Tolerate a missing or extra trailing slash: /calculators and /calculators/ are the
  // same page, and the source pages use both spellings.
  if (r !== '/' && ROUTES.has(r + '/')) return r + '/';
  if (r.endsWith('/') && ROUTES.has(r.slice(0, -1))) return r.slice(0, -1);
  return null;
}

/**
 * Prefix in-set internal links so navigation stays inside the chosen locale.
 * A link to a route NOT in the manifest is left unprefixed on purpose — it points at a
 * page that exists only in English, and sending a user to /es/<that> would 404.
 */
function localizeLinks(html, loc) {
  return html.replace(/(\bhref=")(\/[^"#?]*)([^"]*)(")/g, (m, lead, p, tail, end) => {
    const route = resolveRoute(p);
    if (!route) return m;
    return `${lead}${loc.prefix}${route}${tail}${end}`;
  });
}

/** Point the canonical at this locale's own URL (self-canonical per locale). */
function setCanonical(html, route, loc) {
  return html.replace(
    /(<link\b[^>]*\brel="canonical"[^>]*\bhref=")([^"]*)(")/i,
    (m, a, _old, c) => `${a}${urlFor(route, loc)}${c}`,
  );
}

/**
 * Set <html lang> and <html dir>, both straight from the registry.
 * `dir` was ltr for all 10 Phase-3 locales; ar and ur made it load-bearing in 4C. Nothing
 * here needed changing for that — the value has always come from locales.json — which is
 * the whole argument for reading the registry instead of hardcoding 'ltr'.
 */
function setHtmlLang(html, loc) {
  if (/<html\b[^>]*\blang=/i.test(html)) {
    html = html.replace(/(<html\b[^>]*\blang=")[^"]*(")/i, `$1${loc.code}$2`);
  } else {
    html = html.replace(/<html\b/i, `<html lang="${loc.code}"`);
  }
  return html.replace(/(<html\b[^>]*?)(\s+dir="[^"]*")?(\s*>)/i, `$1 dir="${loc.dir}"$3`);
}

/** Rewrite og:url / twitter:url to the locale URL, and og:locale to the locale code. */
function setSocial(html, route, loc) {
  html = html.replace(
    /(<meta\b[^>]*\b(?:property|name)="(?:og:url|twitter:url)"[^>]*\bcontent=")([^"]*)(")/gi,
    (m, a, _o, c) => `${a}${urlFor(route, loc)}${c}`,
  );
  if (/og:locale/i.test(html)) {
    html = html.replace(
      /(<meta\b[^>]*\bproperty="og:locale"[^>]*\bcontent=")([^"]*)(")/i,
      (m, a, _o, c) => `${a}${loc.code.replace('-', '_')}${c}`,
    );
  }
  return html;
}

const BANNER = (file, code) =>
  `<!-- GENERATED FILE — do not edit. Source: /${file} · locale: ${code}\n` +
  `     Regenerate with: node scripts/i18n/build-locales.mjs -->\n`;

/* ── BIDI ISOLATION ─────────────────────────────────────────────────────────────
 *
 * Latin tokens inside right-to-left prose reorder. Measured in-browser, not assumed: a
 * token reorders when it STARTS with a neutral character or a digit. "C-3" and
 * "WCL §15(3)" are safe because they open with a strong Latin letter, but "§15(3)"
 * renders ")3(15§" and "400.1-OC" renders "OC-400.1" — a DIFFERENT and entirely plausible
 * form number, which a worker then fails to match against the paper in their hand.
 *
 * WHY THIS RUNS AT EMIT TIME AND NOT AS A PASS OVER THE CATALOG
 *
 * The app does isolate its catalogs directly (scripts/isolate-rtl.mjs, U+2068/U+2069),
 * and copying that here would be wrong. This site splices one catalog value into THREE
 * kinds of slot, and 85 keys are used in more than one kind at once — a FAQ answer is
 * visible prose AND a JSON-LD string; a heading is text AND an og:title attribute. A
 * <bdi> written into the catalog would be correct in the first and render as the literal
 * characters "<bdi>" in the other two, in a tooltip or a Google rich result. There is no
 * per-key choice that is right, because the key is not the unit — the SLOT is.
 *
 *   text slot  -> <bdi>. Real markup, which is what the site wants: it survives a copy
 *                 into a CMS, is visible in view-source, and browsers apply
 *                 unicode-bidi: isolate to it by UA default.
 *   attr slot  -> U+2068 FSI / U+2069 PDI. An attribute value cannot carry markup, but it
 *                 carries these characters fine, and they are invisible when rendered.
 *   JSON-LD    -> NOTHING. Structured data is parsed by machines and never laid out
 *                 bidirectionally, so isolation buys no correctness — while invisible
 *                 control characters in a snippet Google may echo back is a real cost.
 *
 * ...WITH ONE EXCEPTION THAT IS NOT OPTIONAL. <title> and <textarea> are RCDATA and
 * <option> is text-only: markup inside them does NOT parse, it renders as the literal
 * characters. A <bdi> in <title> puts "<bdi>AWW</bdi>" in the browser tab and in the
 * Google result. These are text slots by the extractor's classification but must be
 * isolated the ATTRIBUTE way. Caught by looking at generated output rather than by
 * reasoning about it — the first build did exactly this to every localized <title>.
 *
 * Idempotent: a token already inside a <bdi> or an FSI…PDI pair is left alone, so
 * re-running the build never nests.
 */
const FSI = '⁨', PDI = '⁩';
const DNT_TERMS = (() => {
  try {
    const g = JSON.parse(fs.readFileSync(path.join(ROOT, 'i18n/glossary.json'), 'utf8'));
    // LONGEST FIRST. "New York State Workers' Compensation Board" contains "Workers'
    // Compensation Board"; matching the short one first isolates the tail and leaves the
    // head bare, which is worse than either whole option.
    return [...(g.doNotTranslate || [])].sort((a, b) => b.length - a.length);
  } catch { return []; }
})();

const escRe = (t) => t.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
/** Word-bounded so "Pro" cannot match inside "Profile"; whitespace-tolerant so a glossary
 *  "§ 15(3)" matches copy written "§15(3)". Kept identical to the gate's matcher. */
const dntRe = (t) =>
  new RegExp(`(?<![A-Za-z0-9])${escRe(t).replace(/\\?\s+/g, '\\s*')}(?![A-Za-z0-9])`, 'g');

/** Character ranges already isolated, by either mechanism, so we never nest. */
function isolatedRanges(s) {
  const out = [];
  for (const m of s.matchAll(/<bdi\b[^>]*>[\s\S]*?<\/bdi>/g)) out.push([m.index, m.index + m[0].length - 1]);
  let depth = 0, start = -1;
  for (let i = 0; i < s.length; i++) {
    if (s[i] === FSI) { if (depth === 0) start = i; depth++; }
    else if (s[i] === PDI && depth > 0) { depth--; if (!depth) out.push([start, i]); }
  }
  return out;
}

/** Elements whose content is RCDATA or text-only: markup does not parse inside them. */
const TEXT_ONLY_TAGS = new Set(['title', 'textarea', 'option']);

function isolate(str, rtl, kind) {
  if (!rtl || kind === 'jsonld' || typeof str !== 'string' || !str) return str;
  const wrap = kind === 'chars' ? (t) => FSI + t + PDI : (t) => `<bdi>${t}</bdi>`;
  let out = str;
  for (const term of DNT_TERMS) {
    const ranges = isolatedRanges(out);
    const re = dntRe(term);
    let res = '', last = 0, m;
    while ((m = re.exec(out)) !== null) {
      const a = m.index, b = a + m[0].length - 1;
      if (ranges.some(([s2, e2]) => a >= s2 && b <= e2)) continue;
      res += out.slice(last, a) + wrap(m[0]);
      last = a + m[0].length;
    }
    if (last) out = res + out.slice(last);
  }
  return out;
}

/**
 * Substitute a locale's strings into the page by byte offset, using the slot table that
 * the extractor recorded against the annotated English source.
 *
 * Offsets rather than a DOM walk, so this script needs no HTML parser and the repo stays
 * dependency-free — which is what lets the site keep deploying as pure static with no
 * build step. The trade is that the offsets are only valid for the exact bytes they were
 * measured against, so every file is sha256-checked first and a mismatch is fatal.
 *
 * A missing or empty translation falls through to English, key by key — the same
 * behaviour as the app's catalog, so a half-translated locale renders as a mix rather
 * than as blanks.
 */
function substitute(html, file, catalog, enUrl, locUrl, loc) {
  const rec = SLOTS[file];
  if (!rec) return html;

  const rtl = loc.dir === 'rtl';
  // A missing catalog used to return here. It cannot any more: an RTL locale with no
  // catalog yet still needs its English fallback isolated (see the untranslated branch
  // below) and its JSON-LD self-URLs retargeted at its own pages. Returning early left
  // /ar/ and /ur/ advertising the ENGLISH url in their structured data while their
  // <link rel=canonical> said otherwise — the two contradicting each other is worse than
  // either alone. LTR locales without a catalog keep the old behaviour exactly.
  if (!catalog && !rtl) return html;
  const val = (k) => {
    const v = k.split('.').reduce((o, kk) => (o == null ? undefined : o[kk]), catalog);
    return typeof v === 'string' && v !== '' ? v : null;
  };

  // JSON-LD slots share a block: parse once, set every pointer, re-serialize once.
  const jsonBlocks = new Map();
  for (const s of rec.slots) {
    if (!s.j) continue;
    const id = `${s.s}:${s.e}`;
    if (!jsonBlocks.has(id)) jsonBlocks.set(id, { s: s.s, e: s.e, ptrs: [] });
    jsonBlocks.get(id).ptrs.push(s);
  }

  const edits = [];
  for (const s of rec.slots) {
    if (s.j) continue;
    const chars = s.a || TEXT_ONLY_TAGS.has(s.t);   // markup would render literally
    const v = val(s.k);

    if (v === null) {
      // UNTRANSLATED — the value falls through to English, key by key, so a partly
      // translated locale renders as a mix rather than as blanks. In an RTL page that
      // fallback is not merely untranslated, it is MIS-RENDERED: an English sentence in
      // an RTL paragraph has its trailing punctuation resolved to the wrong side, so
      // "I was hurt at work." displays as ".I was hurt at work". Every neutral character
      // at a run boundary moves. Seen on the first /ar/ build, which carried English copy
      // throughout, and it would recur on every key still outstanding during the
      // translation pass — which is most of them, for most of that pass.
      //
      // Isolating the fallback fixes it: <bdi> defaults to dir=auto, so the run resolves
      // from its own first strong character. Costs nothing once the key IS translated,
      // because then this branch never runs.
      if (!rtl) continue;
      const src = html.slice(s.s, s.e);
      if (!src.trim()) continue;
      edits.push({ s: s.s, e: s.e,
                   text: chars ? (s.a ? escapeAttr(FSI + src + PDI) : FSI + src + PDI)
                               : `<bdi>${src}</bdi>` });
      continue;
    }

    const iso = isolate(v, rtl, chars ? 'chars' : 'markup');
    edits.push({ s: s.s, e: s.e, text: s.a ? escapeAttr(iso) : iso });
  }
  for (const [, blk] of jsonBlocks) {
    let data;
    try { data = JSON.parse(html.slice(blk.s, blk.e)); } catch { continue; }
    let touched = false;
    for (const p of blk.ptrs) {
      const v = val(p.k);
      if (v === null) continue;
      const path = p.j.split('/').filter(Boolean);
      let cur = data;
      for (let i = 0; i < path.length - 1 && cur != null; i++) cur = cur[path[i]];
      if (cur && typeof cur === 'object') { cur[path[path.length - 1]] = v; touched = true; }
    }
    // Any self-URL inside the block must point at THIS locale's page, or the structured
    // data contradicts the canonical we just rewrote.
    const retarget = (o) => {
      if (Array.isArray(o)) return o.forEach(retarget);
      if (!o || typeof o !== 'object') return;
      for (const [k, v] of Object.entries(o)) {
        if (typeof v === 'string') { if (v === enUrl) { o[k] = locUrl; touched = true; } }
        else retarget(v);
      }
    };
    retarget(data);
    if (touched) edits.push({ s: blk.s, e: blk.e, text: '\n' + JSON.stringify(data, null, 2) + '\n' });
  }

  edits.sort((a, b) => b.s - a.s);        // back-to-front so earlier offsets stay valid
  let out = html;
  for (const ed of edits) out = out.slice(0, ed.s) + ed.text + out.slice(ed.e);
  return out;
}

/** Attribute values are spliced inside double quotes, so a literal `"` must be escaped. */
const escapeAttr = (s) => s.replace(/"/g, '&quot;');

/**
 * Convenience-translation notice, injected at the top of <body> on the LOCALE copies of
 * the legal pages only (pages flagged legalNotice in the manifest). English never gets it
 * — English is the governing version, so the line would be nonsense there.
 *
 * It renders from the catalog, so it is reviewed text in every locale rather than model
 * free-text, and it falls back to the English sentence if a locale is missing the key.
 */
function injectLegalNotice(html, catalog, loc) {
  const val = catalog && catalog.shared && catalog.shared.translationNotice;
  const text = (typeof val === 'string' && val !== '') ? val : EN_NOTICE;
  const banner =
    `<div class="i18n-translation-notice" role="note" lang="${loc.code}">${text}</div>\n`;
  const m = html.match(/<body\b[^>]*>/i);
  if (!m) return html;
  const at = m.index + m[0].length;
  return html.slice(0, at) + '\n' + banner + html.slice(at);
}

const EN_NOTICE = (() => {
  try {
    const en = JSON.parse(fs.readFileSync(path.join(ROOT, 'i18n/en.json'), 'utf8'));
    return en.shared.translationNotice;
  } catch { return 'This translation is provided for convenience; the English version governs.'; }
})();

// ---------------------------------------------------------------------------

const written = [];
const stale = [];

function emit(file, content) {
  const abs = path.join(ROOT, file);
  const cur = fs.existsSync(abs) ? fs.readFileSync(abs, 'utf8') : null;
  if (cur === content) return;
  if (CHECK) { stale.push(file); return; }
  fs.mkdirSync(path.dirname(abs), { recursive: true });
  fs.writeFileSync(abs, content);
  written.push(file);
}

for (const page of PAGES) {
  const srcAbs = path.join(ROOT, page.file);
  if (!fs.existsSync(srcAbs)) throw new Error(`manifest lists a missing file: ${page.file}`);
  const original = fs.readFileSync(srcAbs, 'utf8');

  // Slot offsets are measured against the STRIPPED source — the page with every
  // generated block removed. Measuring against the assembled page instead would mean any
  // change to a generated block's size shifted every body slot and invalidated the whole
  // table; this way blocks can grow or shrink freely.
  //
  // The hash still guards the thing that actually matters: if the English COPY was edited
  // since extraction, every offset is wrong and substituting would silently corrupt all
  // nine locales, so refuse rather than guess.
  const base = stripGenerated(original);
  const rec = SLOTS[page.file];
  if (rec) {
    const sha = crypto.createHash('sha256').update(base).digest('hex');
    if (sha !== rec.sha256) {
      throw new Error(
        `${page.file} changed since extraction — i18n/.slots.json offsets are stale.\n` +
        `Re-run the extractor before building locales.`);
    }
  }

  // 1. English source: generated blocks only. Copy is byte-unchanged.
  emit(page.file, injectHead(base, page.route, 'en'));

  // 2. One copy per prefixed locale.
  //    Substitution happens FIRST, on the stripped bytes the offsets were measured
  //    against. The URL/lang rewrites run after, so a link inside a translated paragraph
  //    still gets locale-prefixed.
  for (const loc of TARGETS) {
    let out = substitute(base, page.file, loadCatalog(loc.code), urlFor(page.route, ALL[0]), urlFor(page.route, loc), loc);
    out = absolutizeRefs(out, page.file);
    out = setHtmlLang(out, loc);
    out = setCanonical(out, page.route, loc);
    out = setSocial(out, page.route, loc);
    out = localizeLinks(out, loc);
    out = injectHead(out, page.route, loc.code);
    if (page.legalNotice) out = injectLegalNotice(out, loadCatalog(loc.code), loc);
    out = BANNER(page.file, loc.code) + out;
    emit(path.relative(ROOT, outFor(page.file, loc)), out);
  }
}

if (CHECK) {
  if (stale.length) {
    console.error(`STALE — ${stale.length} generated file(s) out of date:\n  ` + stale.slice(0, 20).join('\n  '));
    console.error('\nRun: node scripts/i18n/build-locales.mjs');
    process.exit(1);
  }
  console.log(`OK — all ${PAGES.length} pages × ${TARGETS.length} locales are current.`);
} else {
  console.log(`Wrote ${written.length} file(s).`);
  console.log(`  ${PAGES.length} English sources (hreflang + runtime injected)`);
  console.log(`  ${PAGES.length * TARGETS.length} locale pages across ${TARGETS.length} locales`);
}
