#!/usr/bin/env node
/**
 * Phase 3 — locale page generator for thecompdesk.com.
 *
 * Reads the English source pages listed in i18n/pages.json and emits one copy per
 * locale under /<locale>/<same path>. English stays at the ROOT, untouched except for
 * the hreflang block and the locale-runtime script tag.
 *
 * Stage 3A: no catalogs exist yet, so every locale page carries English copy. That is
 * deliberate — routing and persistence get proven before content lands. Stage 3B adds
 * i18n/<locale>.json and translation turns on with no change to this file's structure.
 *
 * Generated pages are COMMITTED, not built on Vercel. The site deploys as pure static
 * with no build command; adding one would put the existing English organic footprint
 * behind a build that can fail. Re-run this script after any English source edit.
 *
 *   node scripts/i18n/build-locales.mjs           # write
 *   node scripts/i18n/build-locales.mjs --check   # verify on-disk output is current (CI gate)
 */
import fs from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(new URL('../../', import.meta.url).pathname);
const ORIGIN = 'https://thecompdesk.com';
const CHECK = process.argv.includes('--check');

const locales = JSON.parse(fs.readFileSync(path.join(ROOT, 'i18n/locales.json'), 'utf8'));
const manifest = JSON.parse(fs.readFileSync(path.join(ROOT, 'i18n/pages.json'), 'utf8'));

const TARGETS = locales.locales.filter((l) => l.prefix);          // the 9 prefixed locales
const ALL = locales.locales;                                       // incl. en at root
const PAGES = manifest.pages;
const ROUTES = new Set(PAGES.map((p) => p.route));

/** Absolute URL for a route in a locale. */
const urlFor = (route, loc) => {
  const prefix = loc.prefix || '';
  if (route === '/') return `${ORIGIN}${prefix}/`;
  return `${ORIGIN}${prefix}${route}`;
};

/** Output file path for a source file in a locale. */
const outFor = (file, loc) => path.join(ROOT, loc.prefix.slice(1), file);

/** Load a locale catalog if it exists (Stage 3B onward). Missing = identity/English. */
function loadCatalog(code) {
  const p = path.join(ROOT, 'i18n', `${code}.json`);
  if (!fs.existsSync(p)) return null;
  return JSON.parse(fs.readFileSync(p, 'utf8'));
}

/**
 * hreflang block. Emits an alternate ONLY for locales that actually have a page at a
 * real URL — which, for every page in the manifest, is all 10. Pages absent from the
 * manifest never reach this function and therefore emit nothing: an hreflang pointing
 * at untranslated content is a duplicate-content signal, strictly worse than omission.
 */
function hreflangBlock(route) {
  const lines = ['  <!-- i18n:hreflang (generated by scripts/i18n/build-locales.mjs — do not hand-edit) -->'];
  for (const l of ALL) {
    lines.push(`  <link rel="alternate" hreflang="${l.code}" href="${urlFor(route, l)}">`);
  }
  lines.push(`  <link rel="alternate" hreflang="x-default" href="${urlFor(route, ALL[0])}">`);
  lines.push('  <!-- /i18n:hreflang -->');
  return lines.join('\n');
}

const HREFLANG_RE = /[ \t]*<!-- i18n:hreflang[\s\S]*?<!-- \/i18n:hreflang -->\n?/g;
const RUNTIME_RE = /[ \t]*<script src="\/js\/i18n-locale\.js" defer><\/script>\n?/g;
const RUNTIME_TAG = '  <script src="/js/i18n-locale.js" defer></script>';

/** Strip any previously-generated i18n block so the script is idempotent. */
const stripGenerated = (html) => html.replace(HREFLANG_RE, '').replace(RUNTIME_RE, '');

/** Insert the hreflang block + runtime tag immediately before </head>. */
function injectHead(html, route) {
  const block = `${hreflangBlock(route)}\n${RUNTIME_TAG}\n`;
  const i = html.search(/<\/head>/i);
  if (i === -1) throw new Error('no </head>');
  return html.slice(0, i) + block + html.slice(i);
}

/**
 * Rewrite document-relative asset refs to absolute so they still resolve one directory
 * deeper under a locale prefix. `../css/app.css` from /calculators/aww would otherwise
 * resolve to /es/css/app.css under /es/calculators/aww and 404.
 * Deliberately skips template-literal interpolations (`${...}`) and every URL scheme.
 */
function absolutizeRefs(html, srcFile) {
  const dir = path.posix.dirname('/' + srcFile.split(path.sep).join('/'));
  return html.replace(
    /(\b(?:src|href)=")((?!https?:|\/\/|\/|#|mailto:|tel:|sms:|data:|javascript:|\$\{)[^"]+)"/g,
    (m, lead, ref) => {
      if (ref.includes('${')) return m;
      const abs = path.posix.normalize(path.posix.join(dir, ref));
      return `${lead}${abs}"`;
    },
  );
}

/**
 * 301 sources in vercel.json whose destination IS in the manifest. Following the alias
 * here keeps a locale visitor in their locale — a link to /privacy would otherwise 301
 * to the ENGLISH /legal/privacy and silently drop them out of Spanish — and saves a hop.
 * Aliases whose destination is not in the manifest (/for-attorneys, /calculators/pro,
 * /home-legacy) are absent on purpose: those pages are English-only.
 */
const ALIASES = {
  '/privacy': '/legal/privacy',
  '/terms': '/legal/terms',
  '/hire-attorney': '/connect-with-attorney',
  '/find-attorney': '/connect-with-attorney',
  '/find-attorney-how-it-works': '/connect-with-attorney',
};

/** Map any written form of a link to its canonical manifest route, or null. */
function resolveRoute(p) {
  let r = p.replace(/\.html$/, '');
  if (ALIASES[r]) r = ALIASES[r];
  if (ROUTES.has(r)) return r;
  // Tolerate a missing or extra trailing slash: /calculators and /calculators/ are the
  // same page, and the source pages use both spellings.
  if (r !== '/' && ROUTES.has(r + '/')) return r + '/';
  if (r.endsWith('/') && ROUTES.has(r.slice(0, -1))) return r.slice(0, -1);
  return null;
}

/**
 * Prefix in-set internal links so navigation stays inside the chosen locale.
 * A link to a route NOT in the manifest is left unprefixed on purpose — it points at a
 * page that exists only in English, and sending a user to /es/<that> would 404.
 */
function localizeLinks(html, loc) {
  return html.replace(/(\bhref=")(\/[^"#?]*)([^"]*)(")/g, (m, lead, p, tail, end) => {
    const route = resolveRoute(p);
    if (!route) return m;
    return `${lead}${loc.prefix}${route}${tail}${end}`;
  });
}

/** Point the canonical at this locale's own URL (self-canonical per locale). */
function setCanonical(html, route, loc) {
  return html.replace(
    /(<link\b[^>]*\brel="canonical"[^>]*\bhref=")([^"]*)(")/i,
    (m, a, _old, c) => `${a}${urlFor(route, loc)}${c}`,
  );
}

/** Set <html lang> (and dir, which is ltr for all 10 Phase-3 locales). */
function setHtmlLang(html, loc) {
  if (/<html\b[^>]*\blang=/i.test(html)) {
    html = html.replace(/(<html\b[^>]*\blang=")[^"]*(")/i, `$1${loc.code}$2`);
  } else {
    html = html.replace(/<html\b/i, `<html lang="${loc.code}"`);
  }
  return html.replace(/(<html\b[^>]*?)(\s+dir="[^"]*")?(\s*>)/i, `$1 dir="${loc.dir}"$3`);
}

/** Rewrite og:url / twitter:url to the locale URL, and og:locale to the locale code. */
function setSocial(html, route, loc) {
  html = html.replace(
    /(<meta\b[^>]*\b(?:property|name)="(?:og:url|twitter:url)"[^>]*\bcontent=")([^"]*)(")/gi,
    (m, a, _o, c) => `${a}${urlFor(route, loc)}${c}`,
  );
  if (/og:locale/i.test(html)) {
    html = html.replace(
      /(<meta\b[^>]*\bproperty="og:locale"[^>]*\bcontent=")([^"]*)(")/i,
      (m, a, _o, c) => `${a}${loc.code.replace('-', '_')}${c}`,
    );
  }
  return html;
}

const BANNER = (file, code) =>
  `<!-- GENERATED FILE — do not edit. Source: /${file} · locale: ${code}\n` +
  `     Regenerate with: node scripts/i18n/build-locales.mjs -->\n`;

/** Apply a catalog to the page. No-op in Stage 3A (no catalogs on disk yet). */
function translate(html, catalog) {
  if (!catalog) return html;
  return html.replace(/(<[^>]*\bdata-i18n="([^"]+)"[^>]*>)([\s\S]*?)(<\/)/g, (m, open, key, body, close) => {
    const val = key.split('.').reduce((o, k) => (o == null ? undefined : o[k]), catalog);
    return typeof val === 'string' && val !== '' ? `${open}${val}${close}` : m;
  });
}

// ---------------------------------------------------------------------------

const written = [];
const stale = [];

function emit(file, content) {
  const abs = path.join(ROOT, file);
  const cur = fs.existsSync(abs) ? fs.readFileSync(abs, 'utf8') : null;
  if (cur === content) return;
  if (CHECK) { stale.push(file); return; }
  fs.mkdirSync(path.dirname(abs), { recursive: true });
  fs.writeFileSync(abs, content);
  written.push(file);
}

for (const page of PAGES) {
  const srcAbs = path.join(ROOT, page.file);
  if (!fs.existsSync(srcAbs)) throw new Error(`manifest lists a missing file: ${page.file}`);
  const original = fs.readFileSync(srcAbs, 'utf8');
  const base = stripGenerated(original);

  // 1. English source: hreflang + runtime only. Copy is byte-unchanged.
  emit(page.file, injectHead(base, page.route));

  // 2. One copy per prefixed locale.
  for (const loc of TARGETS) {
    let out = base;
    out = absolutizeRefs(out, page.file);
    out = setHtmlLang(out, loc);
    out = setCanonical(out, page.route, loc);
    out = setSocial(out, page.route, loc);
    out = localizeLinks(out, loc);
    out = injectHead(out, page.route);
    out = translate(out, loadCatalog(loc.code));
    out = BANNER(page.file, loc.code) + out;
    emit(path.relative(ROOT, outFor(page.file, loc)), out);
  }
}

if (CHECK) {
  if (stale.length) {
    console.error(`STALE — ${stale.length} generated file(s) out of date:\n  ` + stale.slice(0, 20).join('\n  '));
    console.error('\nRun: node scripts/i18n/build-locales.mjs');
    process.exit(1);
  }
  console.log(`OK — all ${PAGES.length} pages × ${TARGETS.length} locales are current.`);
} else {
  console.log(`Wrote ${written.length} file(s).`);
  console.log(`  ${PAGES.length} English sources (hreflang + runtime injected)`);
  console.log(`  ${PAGES.length * TARGETS.length} locale pages across ${TARGETS.length} locales`);
}
